/**
 * MR. MAYOR - Infrastructure Analysis Center & Official Report Studio
 * Authority-Only Decision Support System & Official Report Generator (Spec Sections 46 - 68)
 * 
 * Answers the 9 Core Governance Questions:
 *  1. PROJECT IDENTITY
 *  2. WHAT IS THE PROBLEM?
 *  3. WHAT DID MR. MAYOR ANALYZE?
 *  4. WHAT CONFLICTS WERE FOUND?
 *  5. WHAT DOES THE AI PROPOSE?
 *  6. WHY THIS SOLUTION?
 *  7. WHAT WILL IT SAVE?
 *  8. WHAT ARE THE RISKS & MITIGATIONS?
 *  9. WHAT SHOULD EACH DEPARTMENT DO?
 *  10. OFFICIAL MUNICIPAL ANALYSIS REPORT & AUDIT TRAIL
 */

import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  ShieldCheck,
  Lock,
  AlertTriangle,
  CheckCircle2,
  FileText,
  Printer,
  Download,
  Copy,
  Layers,
  Clock,
  Calendar,
  IndianRupee,
  Activity,
  Sliders,
  Check,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  FileCheck,
  ArrowRight,
  ExternalLink,
  ShieldAlert,
  HardHat,
  Eye,
  Info,
  X,
} from 'lucide-react';
import {
  Project,
  InfrastructureAnalysisReport,
  DepartmentActionItem,
  QualityInspectorOperationalView,
  PublicProjectStatusSummary,
} from '../../types';
import { api } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

interface InfrastructureAnalysisCenterProps {
  project: Project;
  onPlanAccepted?: () => void;
  onRefresh?: () => void;
}

export type MunicipalReportType =
  | 'INTERNAL_COORDINATION_REPORT'
  | 'DEPARTMENT_ACTION_REPORT'
  | 'FIELD_EXECUTION_SHEET'
  | 'PUBLIC_PROJECT_STATUS';

export const InfrastructureAnalysisCenter: React.FC<InfrastructureAnalysisCenterProps> = ({
  project,
  onPlanAccepted,
  onRefresh,
}) => {
  const { currentUser } = useAuth();
  const [report, setReport] = useState<InfrastructureAnalysisReport | null>(null);
  const [accessLevel, setAccessLevel] = useState<string>('FULL');
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Official Report Studio State
  const [showOfficialReportModal, setShowOfficialReportModal] = useState<boolean>(false);
  const [selectedReportType, setSelectedReportType] = useState<MunicipalReportType>('INTERNAL_COORDINATION_REPORT');
  const [officialReportData, setOfficialReportData] = useState<any>(null);
  const [isGeneratingReport, setIsGeneratingReport] = useState<boolean>(false);
  const [copiedText, setCopiedText] = useState<boolean>(false);

  // Decision State
  const [isAccepting, setIsAccepting] = useState<boolean>(false);
  const [showRejectModal, setShowRejectModal] = useState<boolean>(false);
  const [rejectReason, setRejectReason] = useState<string>('');
  const [isRejecting, setIsRejecting] = useState<boolean>(false);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  const fetchAnalysis = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await api.getInfrastructureAnalysis(project.id, currentUser?.id);
      setAccessLevel(res.accessLevel);
      setReport(res.report);
    } catch (err: any) {
      console.error('Failed to load analysis:', err);
      setError(err.message || 'ACCESS RESTRICTED: This information is available only to authorized personnel.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalysis();
  }, [project.id, currentUser?.id]);

  const handleGenerateOfficialReport = async (reportType: MunicipalReportType = selectedReportType) => {
    setIsGeneratingReport(true);
    setSelectedReportType(reportType);
    try {
      const res = await api.generateOfficialMunicipalReport(project.id, reportType, currentUser?.id);
      setOfficialReportData(res);
      setShowOfficialReportModal(true);
    } catch (err: any) {
      alert(err.message || 'Failed to generate official report.');
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const handleCopyReportText = () => {
    if (!officialReportData?.report) return;
    const r = officialReportData.report;
    const text = `================================================================================
NASHIK MUNICIPAL CORPORATION • SMART CITY DEVELOPMENT CORP.
OFFICIAL MULTI-AGENCY INFRASTRUCTURE COORDINATION REPORT
Issued under Maharashtra Municipal Corporations Act (MMCA 1949), Section 197
================================================================================

ANALYSIS REF: ${officialReportData.analysisId}
VERSION: ${officialReportData.version}
CLASSIFICATION: RESTRICTED
DATE GENERATED: ${new Date(officialReportData.generatedAt).toLocaleString()}
GENERATED BY: ${officialReportData.generatedBy}

1. PROJECT IDENTIFICATION
- Project: ${r.project?.name} (${r.project?.code})
- Department: ${r.project?.department}
- Corridor: ${r.project?.roadName}
- Budget: ₹${((r.project?.estimatedCostINR || 0) / 10000000).toFixed(2)} Cr

2. WHAT IS THE PROBLEM?
- Headline: ${r.problemStatement?.headline}
- Risk Summary: ${r.problemStatement?.riskSummary}
- Duplicate Excavation Risk: ${r.problemStatement?.duplicateDigsRisk}
- Traffic Impact: ${r.problemStatement?.trafficGridlockRisk}

3. WHAT DID MR. MAYOR ANALYZE?
- Historical V/C Ratio: ${r.whatWasAnalyzed?.historicalVC} (${r.whatWasAnalyzed?.vcCategory})
- Moratorium Status: ${r.whatWasAnalyzed?.recentRestorationStatus}
- Junction Sensitivities: ${r.whatWasAnalyzed?.junctionSensitivities?.join(', ')}

4. AI PROPOSED COORDINATION PLAN
- Selected Plan: ${r.aiProposedSolution?.planName}
- Joint Excavation Window: ${r.aiProposedSolution?.windowDates} (${r.aiProposedSolution?.durationDays} Days)
- Restoration Specification: ${r.aiProposedSolution?.singleRestorationType}

5. QUANTIFIED MUNICIPAL SAVINGS
- Duplicate Excavations Avoided: ${r.whatWillItSave?.excavationsEliminated}
- Patch Restorations Eliminated: ${r.whatWillItSave?.restorationsEliminated}
- Commuter Traffic Delay Reduction: ${r.whatWillItSave?.trafficDisruptionReductionPct}%
- Net Municipal Funds Saved: ₹${r.whatWillItSave?.costSavingsLakhs} Lakhs

6. DEPARTMENT EXECUTION SCHEDULE
${r.departmentActionChecklist?.map((d: DepartmentActionItem) => `[${d.depthHierarchyOrder}] ${d.department} (${d.depthMeters}m Depth) -> Window: ${d.mobilizationDate} to ${d.completionDate} | QC: ${d.postInstallationQC?.[0] || 'Standard'}`).join('\n')}

STATUTORY ENDORSEMENT:
Authorized by Municipal Commissioner / Collector under MMCA 1949 Section 197.
================================================================================`;

    navigator.clipboard.writeText(text);
    setCopiedText(true);
    setTimeout(() => setCopiedText(false), 2500);
  };

  const handleDownloadDoc = () => {
    if (!officialReportData?.report) return;
    const r = officialReportData.report;
    const text = `================================================================================
NASHIK MUNICIPAL CORPORATION • SMART CITY DEVELOPMENT CORP.
OFFICIAL MULTI-AGENCY INFRASTRUCTURE COORDINATION REPORT
Issued under Maharashtra Municipal Corporations Act (MMCA 1949), Section 197
================================================================================

ANALYSIS REF: ${officialReportData.analysisId}
VERSION: ${officialReportData.version}
CLASSIFICATION: RESTRICTED
DATE GENERATED: ${new Date(officialReportData.generatedAt).toLocaleString()}
GENERATED BY: ${officialReportData.generatedBy}

1. PROJECT IDENTIFICATION
- Project: ${r.project?.name} (${r.project?.code})
- Department: ${r.project?.department}
- Corridor: ${r.project?.roadName}
- Budget: ₹${((r.project?.estimatedCostINR || 0) / 10000000).toFixed(2)} Cr

2. WHAT IS THE PROBLEM?
- Headline: ${r.problemStatement?.headline}
- Risk Summary: ${r.problemStatement?.riskSummary}
- Duplicate Excavation Risk: ${r.problemStatement?.duplicateDigsRisk}
- Traffic Impact: ${r.problemStatement?.trafficGridlockRisk}

3. WHAT DID MR. MAYOR ANALYZE?
- Historical V/C Ratio: ${r.whatWasAnalyzed?.historicalVC} (${r.whatWasAnalyzed?.vcCategory})
- Moratorium Status: ${r.whatWasAnalyzed?.recentRestorationStatus}
- Junction Sensitivities: ${r.whatWasAnalyzed?.junctionSensitivities?.join(', ')}

4. AI PROPOSED COORDINATION PLAN
- Selected Plan: ${r.aiProposedSolution?.planName}
- Joint Excavation Window: ${r.aiProposedSolution?.windowDates} (${r.aiProposedSolution?.durationDays} Days)
- Restoration Specification: ${r.aiProposedSolution?.singleRestorationType}

5. QUANTIFIED MUNICIPAL SAVINGS
- Duplicate Excavations Avoided: ${r.whatWillItSave?.excavationsEliminated}
- Patch Restorations Eliminated: ${r.whatWillItSave?.restorationsEliminated}
- Commuter Traffic Delay Reduction: ${r.whatWillItSave?.trafficDisruptionReductionPct}%
- Net Municipal Funds Saved: ₹${r.whatWillItSave?.costSavingsLakhs} Lakhs

6. DEPARTMENT EXECUTION SCHEDULE
${r.departmentActionChecklist?.map((d: DepartmentActionItem) => `[${d.depthHierarchyOrder}] ${d.department} (${d.depthMeters}m Depth) -> Window: ${d.mobilizationDate} to ${d.completionDate} | QC: ${d.postInstallationQC?.[0] || 'Standard'}`).join('\n')}

STATUTORY ENDORSEMENT:
Authorized by Municipal Commissioner / Collector under MMCA 1949 Section 197.
================================================================================`;

    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `MR_MAYOR_OFFICIAL_REPORT_${officialReportData.analysisId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleAcceptPlan = async () => {
    if (!report) return;
    setIsAccepting(true);
    setFeedback(null);
    try {
      const res = await api.acceptCoordinationPlan({
        projectId: project.id,
        planId: report.aiProposedSolution.selectedPlanId,
        officer: currentUser?.name || 'Executive Officer',
        designation: currentUser?.designation || 'Authority',
        department: currentUser?.department || project.department,
        notes: `Accepted official AI Infrastructure Coordination Plan ${report.analysisId} under MMCA 1949 Section 197.`,
      });

      setFeedback({
        type: 'success',
        text: `Official plan accepted! Synchronized into Coordination Cluster ${res.cluster.clusterCode}.`,
      });

      if (onPlanAccepted) onPlanAccepted();
      if (onRefresh) onRefresh();
    } catch (err: any) {
      setFeedback({ type: 'error', text: err.message || 'Failed to authorize plan.' });
    } finally {
      setIsAccepting(false);
    }
  };

  const handleRejectPlan = async () => {
    if (!rejectReason.trim()) {
      alert('Statutory reason is required by municipal audit policy.');
      return;
    }
    setIsRejecting(true);
    try {
      await api.rejectCoordinationPlan({
        projectId: project.id,
        planId: report?.aiProposedSolution?.selectedPlanId || 'PLAN_A',
        reason: rejectReason,
        officer: currentUser?.name,
        designation: currentUser?.designation,
        department: currentUser?.department,
      });

      setShowRejectModal(false);
      setFeedback({
        type: 'success',
        text: 'Coordination recommendation rejected and statutory reason logged in municipal audit ledger.',
      });
      if (onRefresh) onRefresh();
    } catch (err: any) {
      alert(err.message || 'Failed to log rejection.');
    } finally {
      setIsRejecting(false);
    }
  };

  // -------------------------------------------------------------
  // LOADING STATE
  // -------------------------------------------------------------
  if (isLoading) {
    return (
      <div className="p-12 text-center space-y-3">
        <div className="w-10 h-10 border-4 border-blue-900 border-t-transparent rounded-full animate-spin mx-auto" />
        <div className="text-xs font-bold text-slate-700">Analyzing Subsurface Infrastructure & Corridor Baseline...</div>
        <p className="text-[11px] text-slate-500">Cross-referencing CTTP 2016 traffic data, geotechnical depth rules, and multi-agency lookahead windows.</p>
      </div>
    );
  }

  // -------------------------------------------------------------
  // ACCESS RESTRICTED / DENIED VIEW (Section 65)
  // -------------------------------------------------------------
  if (error || accessLevel === 'DENIED') {
    return (
      <div className="p-8 rounded-3xl bg-slate-50 border border-slate-200 text-center space-y-4 max-w-lg mx-auto shadow-xs">
        <div className="w-12 h-12 rounded-2xl bg-amber-50 text-amber-700 flex items-center justify-center mx-auto border border-amber-200">
          <Lock className="w-6 h-6" />
        </div>
        <div className="space-y-1">
          <h3 className="font-bold text-slate-900 text-sm tracking-wide uppercase">
            Access Restricted
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            This information is available only to authorized municipal decision-makers and department officers.
          </p>
        </div>
        <div className="pt-2 text-[11px] text-slate-400">
          Logged as: <strong className="text-slate-700">{currentUser?.name || 'Public User'}</strong> ({currentUser?.role || 'CITIZEN'})
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="p-8 text-center bg-slate-50 rounded-2xl border border-slate-200 space-y-3">
        <AlertTriangle className="w-8 h-8 text-amber-600 mx-auto" />
        <h3 className="font-bold text-slate-900 text-sm">Analysis Not Yet Generated</h3>
        <p className="text-xs text-slate-500 max-w-md mx-auto">
          No analysis report is currently available for this project. Run pre-analysis check or refresh the analysis engine.
        </p>
        <button
          onClick={() => fetchAnalysis()}
          className="px-4 py-2 bg-blue-900 text-white rounded-xl text-xs font-bold hover:bg-blue-950 transition-colors"
        >
          Generate Infrastructure Analysis
        </button>
      </div>
    );
  }

  // -------------------------------------------------------------
  // QUALITY INSPECTOR OPERATIONAL VIEW (Section 51)
  // -------------------------------------------------------------
  if (accessLevel === 'INSPECTOR_OPERATIONAL' && currentUser?.role === 'INSPECTOR') {
    const inspectorData = report as unknown as QualityInspectorOperationalView;
    return (
      <div className="space-y-5">
        <div className="p-5 rounded-2xl bg-emerald-950 text-white shadow-md border border-emerald-900 flex flex-wrap items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Eye className="w-5 h-5 text-emerald-400" />
              <h2 className="text-base font-bold text-white tracking-wide">
                Field Quality & Safety Inspection View
              </h2>
            </div>
            <p className="text-xs text-emerald-200">
              Operational checklist and compaction density verification for on-site QC inspectors.
            </p>
          </div>
          <button
            onClick={() => handleGenerateOfficialReport('FIELD_EXECUTION_SHEET')}
            disabled={isGeneratingReport}
            className="px-3.5 py-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-600 text-white text-xs font-bold transition-all shadow-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Inspection Sheet</span>
          </button>
        </div>

        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 text-[10px] uppercase font-bold">Project Code</span>
              <div className="font-bold text-slate-900 font-mono mt-0.5">{inspectorData?.projectCode || project.code}</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 text-[10px] uppercase font-bold">Approved Window</span>
              <div className="font-bold text-slate-900 mt-0.5">{inspectorData?.approvedWorkWindow || 'Current Phase'}</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 text-[10px] uppercase font-bold">EPC Contractor</span>
              <div className="font-bold text-slate-900 mt-0.5">{inspectorData?.contractor || project.contractorName}</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-400 text-[10px] uppercase font-bold">Target Depth</span>
              <div className="font-bold text-blue-700 font-mono mt-0.5">{inspectorData?.depthMeters || 1.8}m Depth</div>
            </div>
          </div>

          <div className="space-y-2">
            <h4 className="font-bold text-xs text-slate-900 uppercase tracking-wider">
              Mandatory Quality & Compaction Checklist:
            </h4>
            <div className="space-y-2">
              {(inspectorData?.inspectionChecklist || [
                { item: 'Trench excavation depth verified with laser level', mandatory: true, checked: true },
                { item: 'Hard safety barricades with retro-reflective sheeting active', mandatory: true, checked: true },
                { item: 'Granular Sub-Base (GSB) compaction passed at 95%+ Proctor Density', mandatory: true, checked: false },
                { item: 'Final Bituminous Concrete (BC) resurfacing flush with existing road', mandatory: true, checked: false },
              ]).map((chk, i) => (
                <label
                  key={i}
                  className="p-3 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-3 text-xs cursor-pointer hover:bg-slate-100"
                >
                  <input
                    type="checkbox"
                    defaultChecked={chk.checked}
                    className="mt-0.5 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"
                  />
                  <div className="space-y-0.5">
                    <span className="font-medium text-slate-800">{chk.item}</span>
                    {chk.mandatory && (
                      <span className="ml-2 px-1.5 py-0.2 rounded text-[9px] font-bold bg-red-100 text-red-700">
                        MANDATORY
                      </span>
                    )}
                  </div>
                </label>
              ))}
            </div>
          </div>

          <div className="flex justify-end pt-2">
            <button
              onClick={() => alert('Inspection checklist signed and verified.')}
              className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-sm transition-all flex items-center gap-1.5 cursor-pointer"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>Submit Quality Verification</span>
            </button>
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // PUBLIC PROJECT STATUS VIEW (Section 53)
  // -------------------------------------------------------------
  if (accessLevel === 'PUBLIC' || currentUser?.role === 'CITIZEN') {
    const publicData = report as unknown as PublicProjectStatusSummary;
    return (
      <div className="p-6 rounded-3xl bg-white border border-slate-200 shadow-xs space-y-4 max-w-xl mx-auto text-xs">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <Info className="w-4 h-4 text-blue-600" />
            <h3 className="font-bold text-slate-900 text-sm">Public Project Status</h3>
          </div>
          <button
            onClick={() => handleGenerateOfficialReport('PUBLIC_PROJECT_STATUS')}
            disabled={isGeneratingReport}
            className="px-2.5 py-1 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-[11px] font-bold transition-all shadow-xs flex items-center gap-1 cursor-pointer"
          >
            <Printer className="w-3 h-3" />
            <span>Print Advisory</span>
          </button>
        </div>

        <div className="space-y-2">
          <div>
            <span className="text-slate-400 text-[10px] uppercase font-bold">Corridor</span>
            <div className="font-bold text-slate-900 text-sm mt-0.5">{publicData?.roadName || project.roadName}</div>
          </div>
          <div>
            <span className="text-slate-400 text-[10px] uppercase font-bold">Execution Timeline</span>
            <div className="font-medium text-slate-800 mt-0.5">{publicData?.expectedTimeline || 'September 2026'}</div>
          </div>
          <div className="p-3 rounded-xl bg-blue-50 border border-blue-100 text-blue-900">
            <strong>Traffic Advisory: </strong> {publicData?.trafficAdvisory || 'Partial lane restrictions. Motorists are advised to follow signage.'}
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------
  // FULL / DEPARTMENT-SCOPED INFRASTRUCTURE ANALYSIS CENTER
  // -------------------------------------------------------------
  const isTopAuthority = currentUser?.role === 'COMMISSIONER' || currentUser?.role === 'ADMIN';

  return (
    <div className="space-y-6">
      {/* 1. TOP STATUTORY HEADER & SECURITY CLASSIFICATION BAR */}
      <div className="p-5 rounded-2xl bg-gradient-to-r from-slate-900 via-blue-950 to-slate-900 text-white shadow-md border border-slate-800 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-blue-400" />
              <h2 className="text-base font-bold text-white tracking-wide">
                Infrastructure Analysis Center
              </h2>
              <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-red-500/20 text-red-300 border border-red-400/30 uppercase">
                {report?.sensitivity || 'RESTRICTED'}
              </span>
            </div>
            <p className="text-xs text-slate-300">
              Authority-Only Decision Support Engine — Comprehensive 9-Point Cross-Utility Engineering Assessment.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => handleGenerateOfficialReport('INTERNAL_COORDINATION_REPORT')}
              disabled={isGeneratingReport}
              className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition-all shadow-md flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <FileText className="w-4 h-4 text-indigo-200" />
              <span>{isGeneratingReport ? 'Generating...' : 'Generate Official Municipal Report'}</span>
            </button>
            <button
              onClick={() => fetchAnalysis()}
              disabled={isLoading}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold transition-all shadow-xs flex items-center justify-center cursor-pointer disabled:opacity-50"
              title="Refresh Analysis"
            >
              <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
            </button>
          </div>
        </div>

        {/* Audit Metadata Stamp */}
        <div className="pt-2 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-[11px] text-slate-400">
          <div className="flex items-center gap-3">
            <span>Analysis ID: <strong className="text-white font-mono">{report?.analysisId || 'ANA-2026-001'}</strong></span>
            <span>Version: <strong className="text-white font-mono">{report?.version || '1.2'}</strong></span>
            <span>Generated By: <strong className="text-white">{report?.generatedBy}</strong> ({report?.generatedByRole})</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-blue-500/20 text-blue-300 border border-blue-400/30">
              {accessLevel === 'FULL' ? 'LEVEL 1: FULL AUTHORITY ACCESS' : 'LEVEL 2/3: DEPT SCOPED ACCESS'}
            </span>
          </div>
        </div>
      </div>

      {/* FEEDBACK BANNER */}
      {feedback && (
        <div
          className={`p-4 rounded-xl text-xs flex items-center justify-between gap-3 border ${
            feedback.type === 'success'
              ? 'bg-emerald-50 text-emerald-900 border-emerald-200'
              : 'bg-red-50 text-red-900 border-red-200'
          }`}
        >
          <div className="flex items-center gap-2">
            {feedback.type === 'success' ? (
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            ) : (
              <AlertTriangle className="w-4 h-4 text-red-600" />
            )}
            <span>{feedback.text}</span>
          </div>
          <button onClick={() => setFeedback(null)} className="text-slate-400 hover:text-slate-600 font-bold"><X className="w-4 h-4" /></button>
        </div>
      )}

      {/* 2. THE 9 CORE GOVERNANCE QUESTIONS */}
      {report && (
        <div className="space-y-4">
          {/* Q1: PROJECT IDENTITY */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-800 font-bold flex items-center justify-center text-xs">
                  1
                </span>
                <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                  Project Identity & Statutory Scope
                </h3>
              </div>
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-blue-50 text-blue-800 border border-blue-200">
                {project.department}
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Project Name</span>
                <div className="font-bold text-slate-900 mt-0.5">{project.name}</div>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Corridor</span>
                <div className="font-bold text-slate-900 mt-0.5">{project.roadName}</div>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Financial Budget</span>
                <div className="font-bold text-slate-900 mt-0.5 font-mono">₹{(project.estimatedCostINR / 10000000).toFixed(2)} Cr</div>
              </div>
            </div>
          </div>

          {/* Q2: WHAT IS THE PROBLEM? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-2.5">
              <span className="w-6 h-6 rounded-full bg-amber-100 text-amber-800 font-bold flex items-center justify-center text-xs">
                2
              </span>
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                What is the Problem?
              </h3>
            </div>

            <div className="space-y-2 text-xs">
              <div className="font-bold text-amber-900 text-sm">
                {report.problemStatement.headline}
              </div>
              <p className="text-slate-700 leading-relaxed">
                {report.problemStatement.riskSummary}
              </p>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-2.5 pt-2">
                <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 space-y-1">
                  <div className="font-bold text-amber-900 text-[11px] uppercase">Pavement Destruction</div>
                  <p className="text-[11px] text-amber-800">{report.problemStatement.duplicateDigsRisk}</p>
                </div>
                <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                  <div className="font-bold text-purple-900 text-[11px] uppercase">Traffic Gridlock Risk</div>
                  <p className="text-[11px] text-purple-800">{report.problemStatement.trafficGridlockRisk}</p>
                </div>
                <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 space-y-1">
                  <div className="font-bold text-emerald-900 text-[11px] uppercase">Financial Loss Risk</div>
                  <p className="text-[11px] text-emerald-800">{report.problemStatement.pavementDestructionCost}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Q3: WHAT DID MR. MAYOR ANALYZE? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-2.5">
              <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-800 font-bold flex items-center justify-center text-xs">
                3
              </span>
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                What Did MR. MAYOR Analyze?
              </h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-400 text-[10px] uppercase font-bold">CTTP 2016 V/C Baseline</span>
                <div className="font-bold text-slate-900 text-sm font-mono">
                  {report.whatWasAnalyzed.historicalVC} ({report.whatWasAnalyzed.vcCategory})
                </div>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Restoration Moratorium</span>
                <div className="font-bold text-slate-900 text-xs">
                  {report.whatWasAnalyzed.recentRestorationStatus}
                </div>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Junction Sensitivities</span>
                <div className="font-bold text-slate-900 text-xs truncate">
                  {report.whatWasAnalyzed.junctionSensitivities[0] || 'Standard Node'}
                </div>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-400 text-[10px] uppercase font-bold">Seasonal / Kumbh Mandate</span>
                <div className="font-bold text-slate-900 text-xs truncate">
                  {report.whatWasAnalyzed.simhasthaKumbhMandate ? 'Simhastha Priority Corridor' : report.whatWasAnalyzed.monsoonPolicyStatus}
                </div>
              </div>
            </div>
          </div>

          {/* Q4: WHAT CONFLICTS WERE FOUND? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-red-100 text-red-800 font-bold flex items-center justify-center text-xs">
                  4
                </span>
                <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                  What Conflicts Were Found? ({report.conflictsFound.length})
                </h3>
              </div>
              <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-amber-50 text-amber-800 border border-amber-200">
                Cross-Utility Clashes
              </span>
            </div>

            <div className="space-y-2">
              {report.conflictsFound.map((clash, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-red-50/50 border border-red-200 flex flex-wrap items-center justify-between gap-2 text-xs"
                >
                  <div className="space-y-0.5">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-red-900">{clash.pair}</span>
                      <span className="px-2 py-0.2 rounded-full text-[9px] font-bold bg-red-600 text-white">
                        {clash.severity}
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-700">{clash.hazardSummary}</p>
                  </div>
                  <div className="text-[11px] text-slate-500 font-mono">
                    {clash.spatialOverlap} • {clash.temporalOverlap}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Q5: WHAT DOES THE AI PROPOSE? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-800 font-bold flex items-center justify-center text-xs">
                  5
                </span>
                <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                  What Does the AI Propose?
                </h3>
              </div>
              <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold bg-emerald-600 text-white uppercase">
                {report.aiProposedSolution.planName}
              </span>
            </div>

            <div className="space-y-3 text-xs">
              <p className="text-slate-700 leading-relaxed font-medium">
                {report.aiProposedSolution.summary}
              </p>

              <div className="p-3 rounded-xl bg-blue-50/80 border border-blue-200 flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4 text-blue-600" />
                  <span className="font-bold text-blue-900">
                    Joint Window: {report.aiProposedSolution.windowDates} ({report.aiProposedSolution.durationDays} Days)
                  </span>
                </div>
                <span className="text-[11px] text-blue-800 font-medium">
                  {report.aiProposedSolution.singleRestorationType}
                </span>
              </div>

              {/* Depth-wise sequence */}
              <div className="space-y-1.5 pt-1">
                <span className="text-[11px] font-bold text-slate-700 uppercase tracking-wider">
                  Geotechnical Depth-Wise Execution Sequence:
                </span>
                <div className="space-y-1.5">
                  {report.aiProposedSolution.depthSequence.map((step, idx) => (
                    <div
                      key={idx}
                      className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 flex items-start gap-2 text-xs"
                    >
                      <span className="w-4 h-4 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-[10px] shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span className="text-slate-800 font-mono">{step}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Q6: WHY THIS SOLUTION? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-2.5">
              <span className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-800 font-bold flex items-center justify-center text-xs">
                6
              </span>
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                Why This Solution? (Explainable Engineering Justification)
              </h3>
            </div>

            <div className="space-y-2 text-xs">
              <p className="text-slate-700 leading-relaxed">
                {report.whyThisSolution.engineeringJustification}
              </p>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-slate-600 text-[11px]">
                <strong>Geotechnical Quality: </strong> {report.whyThisSolution.geotechnicalSafety}
              </div>
              <div className="text-[11px] text-slate-500">
                {report.whyThisSolution.scoreExplanation}
              </div>
            </div>
          </div>

          {/* Q7: WHAT WILL IT SAVE? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-2.5">
              <span className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-800 font-bold flex items-center justify-center text-xs">
                7
              </span>
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                What Will It Save?
              </h3>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase font-bold">Avoidable Digs (Modelled)</span>
                <div className="text-2xl font-bold font-mono text-blue-700">
                  {report.whatWillItSave.excavationsEliminated}
                </div>
                <div className="text-[10px] text-slate-500">Eliminated cuts</div>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase font-bold">Restorations (Modelled)</span>
                <div className="text-2xl font-bold font-mono text-emerald-700">
                  {report.whatWillItSave.restorationsEliminated}
                </div>
                <div className="text-[10px] text-slate-500">Replaced by 1 joint seal</div>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase font-bold">Traffic Drop (Modelled)</span>
                <div className="text-2xl font-bold font-mono text-purple-700">
                  -{report.whatWillItSave.trafficDisruptionReductionPct}%
                </div>
                <div className="text-[10px] text-slate-500">Single off-peak closure</div>
              </div>

              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="text-slate-500 text-[10px] uppercase font-bold">Projected Savings</span>
                <div className="text-2xl font-bold font-mono text-emerald-700">
                  ₹{report.whatWillItSave.costSavingsLakhs} L
                </div>
                <div className="text-[10px] text-slate-500">Net municipal savings</div>
              </div>
            </div>
          </div>

          {/* Q8: WHAT ARE THE RISKS & MITIGATIONS? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-2.5">
              <span className="w-6 h-6 rounded-full bg-amber-100 text-amber-800 font-bold flex items-center justify-center text-xs">
                8
              </span>
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                What Are the Risks & Mitigations?
              </h3>
            </div>

            <div className="space-y-2">
              {report.risksAndMitigations.map((rm, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-slate-50 border border-slate-200 flex flex-wrap items-center justify-between gap-3 text-xs"
                >
                  <div className="space-y-0.5 flex-1 min-w-[200px]">
                    <div className="font-bold text-red-900 flex items-center gap-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-red-600 shrink-0" />
                      <span>{rm.risk}</span>
                    </div>
                  </div>
                  <div className="space-y-0.5 flex-1 min-w-[200px] bg-emerald-50/80 p-2 rounded-lg border border-emerald-200 text-emerald-900">
                    <strong>Mitigation: </strong> {rm.mitigation}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Q9: WHAT SHOULD EACH DEPARTMENT DO? */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-800 font-bold flex items-center justify-center text-xs">
                  9
                </span>
                <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">
                  What Should Each Department Do? (Action Checklist)
                </h3>
              </div>
              <span className="text-[11px] text-slate-500">
                Sorted by Geotechnical Depth Hierarchy
              </span>
            </div>

            <div className="space-y-3">
              {report.departmentActionChecklist.map((deptAction) => (
                <div
                  key={deptAction.department}
                  className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2.5 text-xs"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200/80 pb-2">
                    <div className="flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full bg-blue-600 text-white font-bold flex items-center justify-center text-[10px]">
                        {deptAction.depthHierarchyOrder}
                      </span>
                      <span className="font-bold text-slate-900 text-sm">{deptAction.department}</span>
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-white text-slate-700 border border-slate-200">
                        {deptAction.projectCode}
                      </span>
                    </div>

                    <div className="flex items-center gap-2 font-mono text-[11px]">
                      <span className="text-blue-700 font-bold">{deptAction.depthMeters}m Depth</span>
                      <span className="text-slate-400">•</span>
                      <span className="text-slate-600">{deptAction.mobilizationDate} to {deptAction.completionDate}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-2 pt-1 text-[11px]">
                    <div className="p-2.5 rounded-xl bg-white border border-slate-200 space-y-1">
                      <span className="text-slate-500 font-bold uppercase text-[9px]">Prerequisites & Clearances</span>
                      <ul className="space-y-0.5 text-slate-700">
                        {deptAction.preRequisites.map((p, i) => (
                          <li key={i}>• {p}</li>
                        ))}
                      </ul>
                    </div>

                    <div className="p-2.5 rounded-xl bg-white border border-slate-200 space-y-1">
                      <span className="text-slate-500 font-bold uppercase text-[9px]">Safety Mandates</span>
                      <ul className="space-y-0.5 text-red-800">
                        {deptAction.safetyMandates.map((s, i) => (
                          <li key={i}>• {s}</li>
                        ))}
                      </ul>
                    </div>

                    <div className="p-2.5 rounded-xl bg-white border border-slate-200 space-y-1">
                      <span className="text-slate-500 font-bold uppercase text-[9px]">Post-Installation QC Test</span>
                      <ul className="space-y-0.5 text-emerald-800">
                        {deptAction.postInstallationQC.map((q, i) => (
                          <li key={i}>• {q}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* 10. STATUTORY APPROVAL & GOVERNMENT DECISION BAR */}
          {isTopAuthority && (
            <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-sm flex flex-wrap items-center justify-between gap-4">
              <div className="space-y-0.5">
                <div className="font-bold text-xs text-slate-900">
                  Municipal Authority Decision Authorization (MMCA 1949 Sec 197)
                </div>
                <p className="text-[11px] text-slate-500">
                  Authorizing this report issues the synchronized Joint Excavation Order and binds all departments.
                </p>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => setShowRejectModal(true)}
                  className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-red-50 text-slate-700 hover:text-red-700 text-xs font-bold border border-slate-200 transition-all cursor-pointer"
                >
                  Reject Plan
                </button>
                <button
                  onClick={handleAcceptPlan}
                  disabled={isAccepting}
                  className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-md transition-all flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{isAccepting ? 'Binding...' : 'Accept & Issue Municipal Order'}</span>
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* OFFICIAL REPORT STUDIO MODAL (PRINTABLE / EXPORTABLE) */}
      {showOfficialReportModal && officialReportData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-3 md:p-6 bg-slate-950/70 backdrop-blur-sm animate-fade-in">
          <div className="bg-white border border-slate-200 rounded-3xl p-6 max-w-5xl w-full max-h-[92vh] flex flex-col shadow-2xl overflow-hidden">
            {/* Modal Controls Top */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-4 shrink-0">
              <div className="flex items-center gap-2.5">
                <div className="w-9 h-9 rounded-xl bg-indigo-100 text-indigo-700 flex items-center justify-center">
                  <FileCheck className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-sm text-slate-900">
                    Official Municipal Report Studio
                  </h3>
                  <p className="text-[11px] text-slate-500">
                    Standardized statutory reports under Maharashtra Municipal Corporations Act 1949
                  </p>
                </div>
              </div>

              {/* Action Toolbar */}
              <div className="flex flex-wrap items-center gap-2">
                <button
                  onClick={handleCopyReportText}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer shadow-2xs"
                >
                  {copiedText ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedText ? 'Copied to Clipboard!' : 'Copy Text'}</span>
                </button>
                <button
                  onClick={handleDownloadDoc}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer shadow-2xs"
                >
                  <Download className="w-3.5 h-3.5 text-slate-600" />
                  <span>Download Document</span>
                </button>
                <button
                  onClick={() => window.print()}
                  className="px-4 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer shadow-sm"
                >
                  <Printer className="w-3.5 h-3.5 text-slate-300" />
                  <span>Print / PDF</span>
                </button>
                <button
                  onClick={() => setShowOfficialReportModal(false)}
                  className="p-1.5 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 font-bold transition-all cursor-pointer"
                ><X className="w-4 h-4" /></button>
              </div>
            </div>

            {/* Report Type Selector Tabs */}
            <div className="pt-3 pb-2 border-b border-slate-100 flex flex-wrap items-center gap-2 shrink-0">
              <button
                onClick={() => handleGenerateOfficialReport('INTERNAL_COORDINATION_REPORT')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                  selectedReportType === 'INTERNAL_COORDINATION_REPORT'
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900'
                }`}
              >
                Full Municipal Coordination Report
              </button>
              <button
                onClick={() => handleGenerateOfficialReport('DEPARTMENT_ACTION_REPORT')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                  selectedReportType === 'DEPARTMENT_ACTION_REPORT'
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900'
                }`}
              >
                Department Action Schedule
              </button>
              <button
                onClick={() => handleGenerateOfficialReport('FIELD_EXECUTION_SHEET')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                  selectedReportType === 'FIELD_EXECUTION_SHEET'
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900'
                }`}
              >
                Field QC Inspection Sheet
              </button>
              <button
                onClick={() => handleGenerateOfficialReport('PUBLIC_PROJECT_STATUS')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                  selectedReportType === 'PUBLIC_PROJECT_STATUS'
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900'
                }`}
              >
                Public Project Status Advisory
              </button>
            </div>

            {/* Printable Gazette-Styled Body */}
            <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-6 text-slate-900 print:overflow-visible print:p-0">
              <div className="max-w-3xl mx-auto space-y-6 bg-white p-6 md:p-8 border border-slate-300 rounded-2xl shadow-xs print:border-none print:shadow-none print:p-0">
                {/* Formal Municipal Header */}
                <div className="text-center space-y-1.5 border-b-2 border-slate-900 pb-5">
                  <div className="font-bold text-xs uppercase tracking-widest text-slate-600">
                    NASHIK MUNICIPAL CORPORATION • SMART CITY DEVELOPMENT CORP.
                  </div>
                  <h1 className="text-lg font-black uppercase text-slate-950 tracking-wide">
                    {selectedReportType === 'INTERNAL_COORDINATION_REPORT' && 'OFFICIAL MULTI-AGENCY INFRASTRUCTURE COORDINATION REPORT'}
                    {selectedReportType === 'DEPARTMENT_ACTION_REPORT' && 'DEPARTMENT ACTION PLAN & UTILITY EXECUTION SCHEDULE'}
                    {selectedReportType === 'FIELD_EXECUTION_SHEET' && 'FIELD QUALITY INSPECTION & COMPACTION VERIFICATION SHEET'}
                    {selectedReportType === 'PUBLIC_PROJECT_STATUS' && 'PUBLIC INFRASTRUCTURE STATUS & TRAFFIC ADVISORY'}
                  </h1>
                  <div className="text-[11px] text-slate-500 italic">
                    Issued under Maharashtra Municipal Corporations Act (MMCA 1949), Section 197 & Section 201
                  </div>
                </div>

                {/* Formal Document Metadata Table */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] p-3.5 rounded-xl bg-slate-50 border border-slate-200">
                  <div>
                    <span className="text-slate-500 font-bold block text-[10px]">ANALYSIS REF:</span>
                    <span className="font-mono font-bold text-slate-900">{officialReportData.analysisId}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 font-bold block text-[10px]">DOCUMENT VER:</span>
                    <span className="font-mono font-bold text-slate-900">{officialReportData.version}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 font-bold block text-[10px]">CLASSIFICATION:</span>
                    <span className="font-bold text-red-700">RESTRICTED</span>
                  </div>
                  <div>
                    <span className="text-slate-500 font-bold block text-[10px]">DATE ISSUED:</span>
                    <span className="text-slate-900">{new Date(officialReportData.generatedAt).toLocaleDateString()}</span>
                  </div>
                </div>

                {/* Section 1: Executive Scope & Problem */}
                <div className="space-y-2 text-xs">
                  <h4 className="font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1 flex items-center justify-between">
                    <span>1. Project Scope & Risk Assessment</span>
                    <span className="text-[10px] text-slate-500 font-normal font-mono">{officialReportData.report?.project?.roadName}</span>
                  </h4>
                  <p className="leading-relaxed text-slate-700">
                    {officialReportData.report?.problemStatement?.riskSummary}
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1 text-[11px]">
                    <div className="p-2 rounded-lg bg-slate-50 border border-slate-200">
                      <strong>CTTP 2016 Baseline: </strong> {officialReportData.report?.whatWasAnalyzed?.historicalVC} ({officialReportData.report?.whatWasAnalyzed?.vcCategory})
                    </div>
                    <div className="p-2 rounded-lg bg-slate-50 border border-slate-200">
                      <strong>Restoration Status: </strong> {officialReportData.report?.whatWasAnalyzed?.recentRestorationStatus}
                    </div>
                  </div>
                </div>

                {/* Section 2: Synchronized Department Schedule */}
                <div className="space-y-2 text-xs">
                  <h4 className="font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                    2. Coordinated Depth Hierarchy & Department Schedule
                  </h4>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-[11px] border border-slate-200">
                      <thead className="bg-slate-100 text-slate-800 font-bold">
                        <tr>
                          <th className="p-2 border-b">Seq</th>
                          <th className="p-2 border-b">Department</th>
                          <th className="p-2 border-b">Depth</th>
                          <th className="p-2 border-b">Execution Window</th>
                          <th className="p-2 border-b">Mandatory QC / Safety Mandate</th>
                        </tr>
                      </thead>
                      <tbody>
                        {officialReportData.report?.departmentActionChecklist?.map((d: DepartmentActionItem) => (
                          <tr key={d.department} className="border-b hover:bg-slate-50">
                            <td className="p-2 font-bold font-mono text-center">{d.depthHierarchyOrder}</td>
                            <td className="p-2 font-bold">{d.department}</td>
                            <td className="p-2 font-mono text-blue-800">{d.depthMeters}m</td>
                            <td className="p-2 font-mono">{d.mobilizationDate} to {d.completionDate}</td>
                            <td className="p-2 text-slate-600">{d.safetyMandates?.[0] || 'Standard Safety'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Section 3: Quantified Financial & Traffic Savings */}
                <div className="space-y-2 text-xs">
                  <h4 className="font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                    3. Quantified Municipal Savings & Public Benefit
                  </h4>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center text-xs">
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="text-[10px] text-slate-500 font-bold uppercase">Avoided Digs</span>
                      <div className="font-bold text-blue-700 font-mono text-sm">{officialReportData.report?.whatWillItSave?.excavationsEliminated} Cuts</div>
                    </div>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="text-[10px] text-slate-500 font-bold uppercase">Avoided Restorations</span>
                      <div className="font-bold text-emerald-700 font-mono text-sm">{officialReportData.report?.whatWillItSave?.restorationsEliminated} Patches</div>
                    </div>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="text-[10px] text-slate-500 font-bold uppercase">Traffic Delay Reduction</span>
                      <div className="font-bold text-purple-700 font-mono text-sm">-{officialReportData.report?.whatWillItSave?.trafficDisruptionReductionPct}%</div>
                    </div>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                      <span className="text-[10px] text-slate-500 font-bold uppercase">Public Fund Savings</span>
                      <div className="font-bold text-emerald-700 font-mono text-sm">₹{officialReportData.report?.whatWillItSave?.costSavingsLakhs} L</div>
                    </div>
                  </div>
                </div>

                {/* Section 4: Endorsement & Official Signature Stamp */}
                <div className="pt-6 border-t-2 border-slate-900 grid grid-cols-2 gap-8 text-xs">
                  <div className="space-y-1">
                    <div className="font-bold text-slate-900">Generated & Authenticated By:</div>
                    <div className="text-slate-700 font-medium">{officialReportData.generatedBy}</div>
                    <div className="text-[10px] text-slate-400 font-mono">Digital Hash: {officialReportData.report?.auditMetadata?.auditHash || 'NMC-AUTH-VALID'}</div>
                  </div>
                  <div className="space-y-1 text-right">
                    <div className="font-bold text-slate-900">Statutory Municipal Authority:</div>
                    <div className="text-slate-700 font-medium">Municipal Commissioner & District Collector</div>
                    <div className="text-[10px] text-slate-400 font-mono">Seal: MMC Act 1949 / Sec 197 Certified</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* REJECT MODAL */}
      {showRejectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
          <div className="bg-white border border-slate-200 rounded-3xl p-6 max-w-md w-full space-y-4 shadow-2xl">
            <div className="flex items-center gap-2 text-red-600 font-bold text-sm">
              <AlertTriangle className="w-5 h-5" />
              <span>Statutory Override Reason</span>
            </div>
            <p className="text-xs text-slate-600">
              Municipal audit policy requires a formal engineering or administrative justification when rejecting AI coordination recommendations.
            </p>
            <textarea
              rows={3}
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="e.g., Unforeseen high-voltage cable relocation required prior to main pipeline alignment."
              className="w-full p-3 rounded-xl border border-slate-200 text-xs focus:ring-2 focus:ring-red-500/20 focus:border-red-500 outline-hidden"
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setShowRejectModal(false)}
                className="px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-xs font-bold text-slate-700 cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleRejectPlan}
                disabled={isRejecting}
                className="px-4 py-1.5 rounded-xl bg-red-600 hover:bg-red-500 text-white text-xs font-bold cursor-pointer disabled:opacity-50"
              >
                {isRejecting ? 'Logging...' : 'Confirm Rejection'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
